<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>True</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<PlatformTarget>x86</PlatformTarget>
		<AssemblyName>Auto</AssemblyName>
		<Version>1.0.0.0</Version>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Native\SystemUint\bin\SystemUint.Source.dll" Link="SystemUint.Source.dll" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
		<Content Include="Release\Data\Maps\**\*.map" Link="Data\Maps\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
		<Content Include="Release\Data\ToaDo\**\*" Link="Data\ToaDo\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
	</ItemGroup>
</Project>
